cloud:
  aws:
    credentials:
      access-key: AKIARS5K65VDH3DM6H6S
      secrete-key: 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
      useDefaultAwsCredentialsChain: true
    region:
      static: ap-south-1
    stack:
      auto: false


application:
  bucket:
    name: potholebucket


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

security:
  require-ssl: true

#server:
#  port: 443
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:baeldung.p12
#    key-store-password: password
#    key-alias: baeldung
#    key-password: password
#    enabled: true

server:
  port: 8080
#  ssl:
#    enabled: true
#    keyStoreType: PKCS12
#    key-store: classpath:baeldung.p12
#    key-store-password: password
#  http:
#    port: 8079
